### ISSUE TITLE
Issue with aleph 0.4.4 when running twttr on java 10.0.2

### ISSUE THREAD

**Issue by bzg** [chbrown/twttr#4]
`twttr` requires `aleph 0.4.4` but @brejoc reported an [issue](https://github.com/etalab/retweet/pull/1#issuecomment-482097097) when running `twttr` (from my small [retweet](https://github.com/etalab/retweet/) bot) with java from `openjdk version "10.0.2" 2018-07-17`.

I suggest to require `aleph 0.4.6` (the latest stable version now). Thanks!

**Comment by chbrown** [comment]
Okay, I've upgraded aleph (a.o.) as of a4d8cc6 / 3.2.2.

Closing, but I didn't test it with java 10, so if there's still an issue, please follow up :)

**Comment by brejoc** [comment]
Works like a charm. Thanks a lot!
